version: "3"

services:
  app:
    image: aftermarketmonkey_be:latest
    build:
      context: .
    restart: always
    env_file:
      - ./.env.app
    ports:
      - "8005:8000"
    depends_on:
      - db
      - cache-redis


  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    ports:
      - "54325:5432"
    restart: always

  cache-redis:
    image: redis:7.2-rc1-alpine
    volumes:
      - redis_data:/var/lib/redis/data/
    ports:
      - "6385:6379"
    restart: always


volumes:
  postgres_data:
  redis_data:
